<a href="https://colab.research.google.com/github/muzakkialfarisi/MACHINE-LEARNING/blob/master/Text_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('drive/')
import pandas as pd

df = pd.read_csv("drive/My Drive/Colab Notebooks/dataset_sms_spam_v1.csv", nrows=1000)
df.head()

Drive already mounted at drive/; to attempt to forcibly remount, call drive.mount("drive/", force_remount=True).

                                                                                                                                                        Teks  label
0  [PROMO] Beli paket Flash mulai 1GB di MY TELKOMSEL APP dpt EXTRA kuota 2GB 4G LTE dan EXTRA nelpon hingga 100mnt/1hr. Buruan, cek  di tsel.me/mytsel1 S&K      2
1   2.5 GB/30 hari hanya Rp 35 Ribu Spesial buat Anda yang terpilih. Aktifkan sekarang juga di *550*905#. Promo sd 30 Nov 2015.Buruan aktifkan sekarang. S&K      2
2   2016-07-08 11:47:11.Plg Yth, sisa kuota Flash Anda 478KB. Download MyTelkomsel apps di http://tsel.me/tsel utk cek kuota&beli paket Flash atau hub *363#      2
3  2016-08-07 11:29:47.Plg Yth, sisa kuota Flash Anda 7160KB. Download MyTelkomsel apps di http://tsel.me/tsel utk cek kuota&beli paket Flash atau hub *363#      2
4                                          4.5GB/30 hari hanya Rp 55 Ribu Spesial buat anda yang terpilih. Aktifkan sekarang juga di *550*907# Buruan..! SKB      2

In [ ]:
df.shape

(1000, 2)

In [ ]:
df.label.value_counts()

NameError: ignored

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=1000)
vectors = vectorizer.fit_transform(df.Teks)
words_df = pd.DataFrame(vectors.toarray(), columns=vectorizer.get_feature_names())
words_df.head()

    00  000   01  0100   02  021  ...      yang  yaris   yg       yth  yuk  z10
0  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.000000    0.0  0.0  0.000000  0.0  0.0
1  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.153257    0.0  0.0  0.000000  0.0  0.0
2  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.000000    0.0  0.0  0.150746  0.0  0.0
3  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.000000    0.0  0.0  0.155911  0.0  0.0
4  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.195327    0.0  0.0  0.000000  0.0  0.0

[5 rows x 1000 columns]

In [ ]:
X = words_df
y = df.label

In [ ]:
from sklearn.svm import LinearSVC
%time
# Create and train a linear support vector classifier (LinearSVC)
svc = LinearSVC()
svc.fit(X, y)

CPU times: user 23 µs, sys: 0 ns, total: 23 µs
Wall time: 28.1 µs

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [ ]:
pd.set_option("display.max_colwidth", 200)

datatest = pd.DataFrame({'content': [
    "Anda menerima pesan suara dari 082137717205. Telpon 4 utk mendengarkan (tanpa biaya).Yuk dengerin Blog suara dr selebriti favoritmu. Tlp ke 52000",
    "SB FINANCE Melayani Pinjaman; -Khusus USAHA & Ekonomi. -Proses CEPAT dgn Bunga 4% CHAT;082399084569",
    "Maaf, Kami gagal memproses transaksi  Anda dari Kejutan 10 10. Kami akan melakukan refund untuk transaksi ini.",
    "Mohon maaf permintaan Anda tidak dapat dilanjutkan. (nack)",
    "Kode Verifikasi OVO: 4561 JANGAN BERIKAN KODE RAHASIA INI KEPADA SIAPA PUN, TERMASUK PIHAK YANG MENGAKU DARI OVO Hubungi 1500696 untuk bantuan",
    "Dapatkan Samsung Note20 Series FREE kartuHalo sd 60GB/bln slm 1 thn, casback sd 1,5jt & hadiah menarik lainnya hanya di Erafone terdekat & Samsung Store by NASA",
    "WOW! dengan Paket KRING KRING bisa telpon SEPUASNYA ke Tsel + 15mnt ke semua Oprtr mulai 6rb/hari. Aktifkan di *888*369# atau tsel.me/kringkring . Info hub:188",
    "Asalamuallaikum.pripun kabar e??keluarga sehat to yg di jawa??",
    "Atas nama faris, tujuan pemalang, dijemput di stt telkom, keberangkatan hari ini. Bisa minta nomor telepon supirnya?",
    "yaudah buruan sini",
]})
datatest

                                                                                                                                                            content
0                 Anda menerima pesan suara dari 082137717205. Telpon 4 utk mendengarkan (tanpa biaya).Yuk dengerin Blog suara dr selebriti favoritmu. Tlp ke 52000
1                                                               SB FINANCE Melayani Pinjaman; -Khusus USAHA & Ekonomi. -Proses CEPAT dgn Bunga 4% CHAT;082399084569
2                                                    Maaf, Kami gagal memproses transaksi  Anda dari Kejutan 10 10. Kami akan melakukan refund untuk transaksi ini.
3                                                                                                        Mohon maaf permintaan Anda tidak dapat dilanjutkan. (nack)
4                    Kode Verifikasi OVO: 4561 JANGAN BERIKAN KODE RAHASIA INI KEPADA SIAPA PUN, TERMASUK PIHAK YANG MENGAKU DARI OVO Hubungi 1500696 untuk bantuan
5  Dapatkan Samsung Note20 Series FREE kartuHalo sd 60GB/bln slm 1 thn, casback sd 1,5jt & hadiah menarik lainnya hanya di Erafone terdekat & Samsung Store by NASA
6   WOW! dengan Paket KRING KRING bisa telpon SEPUASNYA ke Tsel + 15mnt ke semua Oprtr mulai 6rb/hari. Aktifkan di *888*369# atau tsel.me/kringkring . Info hub:188
7                                                                                                    Asalamuallaikum.pripun kabar e??keluarga sehat to yg di jawa??
8                                              Atas nama faris, tujuan pemalang, dijemput di stt telkom, keberangkatan hari ini. Bisa minta nomor telepon supirnya?
9                                                                                                                                                yaudah buruan sini

In [ ]:
print(vectorizer.get_feature_names())

['00', '000', '01', '0100', '02', '021', '02599875', '06', '07', '08', '09', '10', '100', '1000', '100jt', '100juta', '100mnt', '100rb', '10gb', '10rb', '11', '111', '1166', '12', '123', '13', '14', '15', '150', '1500366', '15jt', '16', '17', '188', '19', '1gb', '1hr', '1jt', '1unit', '1x', '20', '200', '2012', '2013', '2015', '2016', '20ribu', '21', '22', '23', '24', '24jam', '25', '250', '25e477r', '27', '277fg49', '27jt', '29', '2gb', '2jt', '30', '300', '30hr', '31', '345', '35jt', '363', '3care', '3g', '3gb', '3jt', '40', '45', '4500', '45jt', '477bfg7s', '47bl759', '49jt', '4g', '4gb', '50', '500mb', '50rb', '550', '555', '59', '5gb', '5jt', '60', '600', '606', '60hr', '67ytg44', '700', '75', '75jt', '777', '7887', '7hr', '7y7r8k9z', '800', '808', '8500', '88', '888', '889', '8jf2177', '8jt', '900', '919', '94ad653', '99', '999', 'aamiin', 'abis', 'ada', 'adalah', 'agar', 'agen', 'agustus', 'air', 'aja', 'akan', 'akhir', 'akses', 'aktif', 'aktifkan', 'aku', 'alaikum', 'all', 'allah', 'aman', 'ambil', 'anak', 'anda', 'android', 'andromax', 'angka', 'ap', 'apa', 'aplikasi', 'app', 'apps', 'april', 'aq', 'as', 'asa', 'ass', 'assalamu', 'assalamualaikum', 'at', 'atas', 'atasan', 'atau', 'ato', 'atuh', 'avanza', 'axis', 'ayah', 'ayam', 'ayo', 'ayu', 'b8337h9', 'b89c7h9', 'bagi', 'bagus', 'bahwa', 'baik', 'balas', 'bali', 'balik', 'bandung', 'banget', 'bank', 'banyak', 'bapa', 'bapak', 'baru', 'batin', 'bawa', 'bayar', 'bb', 'bbm', 'bebas', 'bebek', 'beda', 'belanja', 'beli', 'belikan', 'belum', 'berangkat', 'berapa', 'berbagi', 'beres', 'bergabung', 'berhasil', 'berhenti', 'berkah', 'berkat', 'berlaku', 'berlangganan', 'berminat', 'bersama', 'berupa', 'besar', 'besok', 'bgt', 'biar', 'biasa', 'biasanya', 'biaya', 'big', 'bikin', 'bila', 'bilang', 'bimatri', 'bimbingan', 'bingung', 'bisa', 'bisi', 'bit', 'blackberry', 'blg', 'blm', 'bln', 'blogspot', 'bni', 'boleh', 'bonus', 'bonusnya', 'booking', 'bpk', 'bpkb', 'bri', 'bro', 'bronet', 'bronet24jam', 'brp', 'bs', 'bsk', 'bsok', 'btpn', 'bu', 'buat', 'buka', 'bukan', 'buktikan', 'bulan', 'bulanan', 'bunga', 'buruan', 'butuh', 'byr', 'call', 'camera', 'cara', 'caranya', 'card', 'care', 'cari', 'cc', 'cek', 'cell', 'center', 'cepat', 'cepet', 'charged', 'chatting', 'co', 'coba', 'cocok', 'com', 'combo', 'controller', 'copy', 'cs', 'cukup', 'cuma', 'd377hi8', 'da', 'daftar', 'daging', 'dakota', 'dalam', 'dan', 'dana', 'dapat', 'dapatkan', 'dari', 'data', 'data_pasien', 'davis', 'deh', 'dengan', 'depan', 'detail', 'dg', 'dgn', 'di', 'dia', 'diaktifkan', 'diberikan', 'dijamin', 'dijual', 'dikantor', 'dikirim', 'dikti', 'diperpanjang', 'disc', 'disini', 'diskon', 'ditransfer', 'dll', 'dlu', 'domestik', 'dong', 'double', 'download', 'dpt', 'dptkan', 'dr', 'dri', 'drs', 'dulu', 'dy', 'edisi', 'eh', 'ekstra', 'enak', 'engga', 'extra', 'fb', 'fl', 'flash', 'for', 'form', 'foto', 'free', 'freedom', 'ga', 'gabung', 'gadget', 'gaes', 'gais', 'gak', 'galeri', 'game', 'games', 'gamesmu', 'gampang', 'ganti', 'gatau', 'gb', 'gebyar', 'gemini', 'get', 'gik', 'gimana', 'gita', 'github', 'gitu', 'gmn', 'go', 'google', 'gpp', 'grab', 'grabcar', 'grapari', 'gratis', 'group', 'gt', 'gtu', 'gunakan', 'guru', 'guys', 'gw', 'habis', 'hadiah', 'hadir', 'haha', 'haji', 'hal', 'hanya', 'harap', 'harga', 'harganya', 'hari', 'harus', 'hasil', 'hayu', 'hehe', 'hemat', 'hg', 'hingga', 'hj', 'hny', 'hobimu', 'honda', 'hot', 'hp', 'hrg', 'http', 'https', 'hub', 'hubungi', 'ibu', 'id', 'ih', 'ijh76k79', 'ikut', 'in', 'indofood', 'indonesia', 'indosat', 'indosatooredoo', 'info', 'info838', 'informasi', 'ini', 'internasional', 'internet', 'internetan', 'invite', 'iphone', 'ir', 'iring', 'isi', 'isiulang', 'itu', 'iya', 'jadi', 'jadwal', 'jajanonline', 'jakarta', 'jam', 'jaminan', 'jangan', 'januari', 'jaringan', 'jatuh', 'jawaban', 'jazz', 'jd', 'jend', 'jg', 'jgn', 'jika', 'jimdo', 'jkt', 'jl', 'joko', 'jt', 'jual', 'juga', 'juke', 'juli', 'jumat', 'juni', 'juta', 'kabarin', 'kalah', 'kalau', 'kali', 'kalian', 'kalo', 'kamar', 'kamera', 'kami', 'kamis', 'kampus', 'kamu', 'kan', 'kang', 'kantor', 'kapan', 'karena', 'karna', 'kartu', 'kasih', 'katanya', 'kayanya', 'ke', 'ke2', 'kejutan', 'kekantor', 'kelik', 'keluar', 'kemana', 'kemudahan', 'kepada', 'keputusan', 'kerja', 'kesana', 'kesempatan', 'kesini', 'ketemu', 'ketik', 'khusus', 'kios', 'kirim', 'kirimin', 'kita', 'klik', 'klo', 'km', 'kntr', 'kode', 'koinmu', 'kok', 'komar', 'konfirmasi', 'kontrak', 'kosan', 'kpd', 'kredit', 'krm', 'krn', 'kta', 'ktk', 'ktp', 'ku', 'kuliah', 'kumpul', 'kunjungi', 'kuota', 'kupon', 'kurang', 'lab', 'lagi', 'lahir', 'lain', 'lainnya', 'lakukan', 'lalu', 'lama', 'langsung', 'lanjut', 'laporan', 'laptop', 'layanan', 'lebih', 'legal', 'lengkap', 'lenkap', 'lewat', 'lg', 'lgsg', 'lia', 'liat', 'libur', 'liburan', 'lihat', 'line', 'listrik', 'loh', 'lokasi', 'lt', 'lte', 'lupa', 'ly', 'm248k81', 'm902cx8j', 'ma', 'maaf', 'mad', 'mah', 'main', 'mainkan', 'makan', 'makanya', 'makasih', 'makin', 'maksudnya', 'malam', 'malem', 'mama', 'mana', 'mandi', 'mandiri', 'maret', 'masa', 'masak', 'masalah', 'masih', 'masuk', 'masukkan', 'mau', 'mb', 'mbah', 'me', 'mei', 'melakukan', 'melalui', 'melanjutkan', 'melayani', 'membeli', 'men', 'menang', 'menarik', 'mendapat', 'mendapatkan', 'mending', 'mendpt', 'mendptkan', 'menerima', 'mengaktifkan', 'mengenai', 'menggunakan', 'menghubungi', 'menikmati', 'menit', 'menjadi', 'menu', 'meraih', 'mereka', 'mh', 'mie', 'mifi', 'min', 'minat', 'minggu', 'minta', 'misal', 'mk', 'mkios', 'mlm', 'mnctv', 'mndpt', 'mndptkan', 'mo', 'mobil', 'modem', 'mohon', 'msh', 'mu', 'muda', 'mudah', 'mulai', 'murah', 'murid', 'my', 'mycare', 'mytelkomsel', 'mytsel1', 'naik', 'nama', 'nama1', 'nanti', 'nasabah', 'nasi', 'nasib', 'nelp', 'nelpon', 'new', 'ngga', 'ngumpul', 'nih', 'nikah', 'nikmati', 'nilai', 'nissan', 'nitip', 'nmr', 'no', 'nomor', 'non', 'nonton', 'normal', 'november', 'ntar', 'ntr', 'nuhun', 'numpang', 'nunggu', 'nuy', 'nya', 'oh', 'ok', 'oke', 'oleh', 'online', 'onyx3', 'ooredoo', 'operator', 'orang', 'org', 'otomatis', 'pada', 'padahal', 'pagi', 'pak', 'pakai', 'pake', 'paket', 'paketnya', 'paling', 'papa', 'pas', 'pasti', 'pastikan', 'pd', 'pelanggan', 'pemakaian', 'pembayaran', 'pembelian', 'pemenang', 'pemesanan', 'pemilik', 'penawaran', 'penerbangan', 'pengirim', 'pengundian', 'penting', 'penuh', 'periode', 'pernah', 'persediaan', 'pertama', 'pesan', 'pesta', 'pilih', 'pin', 'pin_pemenang', 'pindah', 'pinjaman', 'pizza', 'pkl', 'pkt', 'pla', 'planet', 'play', 'plaza', 'plg', 'plgn', 'plus', 'poin', 'polisi', 'pop', 'popmie', 'program', 'promo', 'proses', 'pst', 'pt', 'pukul', 'pulang', 'pulsa', 'pulsamu', 'pusat', 'put', 'rabu', 'raih', 'rawit', 'rb', 'rek', 'rekening', 'rekeningnya', 'remedial', 'resmi', 'ribu', 'rica', 'rp', 'rp25rb', 'rs', 'rumah', 'saat', 'saatnya', 'sabtu', 'sahabat', 'saja', 'sakit', 'salah', 'saldo', 'sale', 'sama', 'sampai', 'sampaikan', 'samsung', 'sana', 'satu', 'saya', 'sayang', 'sbg', 'sblum', 'sd', 'sdh', 'sebagai', 'sebelum', 'sebenernya', 'sebesar', 'segera', 'sekali', 'sekalian', 'sekarang', 'selama', 'selamat', 'semanggi', 'seminar', 'semoga', 'semua', 'sendiri', 'senin', 'sep', 'september', 'sepuasnya', 'sering', 'seru', 'service', 'sesama', 'sesuai', 'setia', 'setiap', 'setuju', 'shop', 'si', 'siang', 'siapa', 'sih', 'silahkan', 'sim', 'simcard', 'simpati', 'sisa', 'situs', 'sjk', 'skb', 'skrg', 'skripsi', 'skrng', 'slamat', 'slmt', 'sma', 'smartfren', 'sms', 'soal', 'soalnya', 'solusi', 'sore', 'spasi', 'spesial', 'sql', 'status', 'sticker', 'stop', 'store', 'studio', 'suami', 'subang', 'sudah', 'sudirman', 'suka', 'sukses', 'super', 'surat', 'suruh', 'survey', 'suzuki', 'sy', 'syarat', 'table', 'tabungan', 'tadi', 'tahu', 'tahun', 'tak', 'tambahan', 'tanah', 'tanpa', 'tanya', 'tap', 'tapi', 'tappromo', 'tarif', 'tariff', 'tau', 'tbk', 'tcash', 'td', 'tdk', 'tea', 'teh', 'tekan', 'telah', 'telepon', 'telkomsel', 'telkomselpoin', 'telp', 'telpon', 'teman', 'tembus', 'temen', 'tempat', 'tempo', 'terakhir', 'terbaru', 'terbatas', 'terdaftar', 'terdekat', 'terima', 'terlalu', 'terpilih', 'tersambung', 'terus', 'tes', 'tetap', 'teteh', 'text', 'tgl', 'thn', 'tidak', 'tiket', 'tinggal', 'tk', 'tks', 'tlh', 'tlp', 'to', 'togel', 'toko', 'tolong', 'torch', 'toyota', 'tp', 'tpi', 'transaksi', 'transfer', 'travel', 'tri', 'tricare', 'trima', 'trims', 'tronik', 'trs', 'tsel', 'tuh', 'tujuan', 'tuk', 'tukar', 'tukarkan', 'tunai', 'tunggu', 'tunjukan', 'tunjukkan', 'turun', 'tv', 'uang', 'uangnya', 'udah', 'udh', 'ujian', 'ulang', 'ultima', 'undi', 'undian', 'unit', 'unlimited', 'unreg', 'untuk', 'untung', 'up', 'upi', 'usah', 'utk', 'v10', 'v5', 'verifikasi', 'via', 'video', 'view', 'volume', 'voucher', 'wa', 'waktu', 'wb', 'we', 'web', 'webnode', 'webs', 'website', 'weekend', 'wendy', 'wib', 'wkwk', 'wkwkwk', 'wow', 'www', 'xl', 'xv', 'xxx', 'ya', 'yaa', 'yaaa', 'yah', 'yang', 'yaris', 'yg', 'yth', 'yuk', 'z10']

In [ ]:
datatest_vectors = vectorizer.transform(datatest.content)
datatest_words_df = pd.DataFrame(datatest_vectors.toarray(), columns=vectorizer.get_feature_names())
datatest_words_df.head()

    00  000   01  0100   02  021  ...      yang  yaris   yg  yth       yuk  z10
0  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.000000    0.0  0.0  0.0  0.319164  0.0
1  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.000000    0.0  0.0  0.0  0.000000  0.0
2  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.000000    0.0  0.0  0.0  0.000000  0.0
3  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.000000    0.0  0.0  0.0  0.000000  0.0
4  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.225042    0.0  0.0  0.0  0.000000  0.0

[5 rows x 1000 columns]

In [ ]:
datatest_words_df.shape

(10, 1000)

In [ ]:
datatest['pred_svc'] = svc.predict(datatest_words_df)

In [ ]:
datatest

                                                                                                                                                            content  pred_svc
0                 Anda menerima pesan suara dari 082137717205. Telpon 4 utk mendengarkan (tanpa biaya).Yuk dengerin Blog suara dr selebriti favoritmu. Tlp ke 52000         1
1                                                               SB FINANCE Melayani Pinjaman; -Khusus USAHA & Ekonomi. -Proses CEPAT dgn Bunga 4% CHAT;082399084569         1
2                                                    Maaf, Kami gagal memproses transaksi  Anda dari Kejutan 10 10. Kami akan melakukan refund untuk transaksi ini.         1
3                                                                                                        Mohon maaf permintaan Anda tidak dapat dilanjutkan. (nack)         0
4                    Kode Verifikasi OVO: 4561 JANGAN BERIKAN KODE RAHASIA INI KEPADA SIAPA PUN, TERMASUK PIHAK YANG MENGAKU DARI OVO Hubungi 1500696 untuk bantuan         2
5  Dapatkan Samsung Note20 Series FREE kartuHalo sd 60GB/bln slm 1 thn, casback sd 1,5jt & hadiah menarik lainnya hanya di Erafone terdekat & Samsung Store by NASA         2
6   WOW! dengan Paket KRING KRING bisa telpon SEPUASNYA ke Tsel + 15mnt ke semua Oprtr mulai 6rb/hari. Aktifkan di *888*369# atau tsel.me/kringkring . Info hub:188         2
7                                                                                                    Asalamuallaikum.pripun kabar e??keluarga sehat to yg di jawa??         0
8                                              Atas nama faris, tujuan pemalang, dijemput di stt telkom, keberangkatan hari ini. Bisa minta nomor telepon supirnya?         0
9                                                                                                                                                yaudah buruan sini         2

In [ ]:
df.head()

                                                                                                                                                        Teks  label
0  [PROMO] Beli paket Flash mulai 1GB di MY TELKOMSEL APP dpt EXTRA kuota 2GB 4G LTE dan EXTRA nelpon hingga 100mnt/1hr. Buruan, cek  di tsel.me/mytsel1 S&K      2
1   2.5 GB/30 hari hanya Rp 35 Ribu Spesial buat Anda yang terpilih. Aktifkan sekarang juga di *550*905#. Promo sd 30 Nov 2015.Buruan aktifkan sekarang. S&K      2
2   2016-07-08 11:47:11.Plg Yth, sisa kuota Flash Anda 478KB. Download MyTelkomsel apps di http://tsel.me/tsel utk cek kuota&beli paket Flash atau hub *363#      2
3  2016-08-07 11:29:47.Plg Yth, sisa kuota Flash Anda 7160KB. Download MyTelkomsel apps di http://tsel.me/tsel utk cek kuota&beli paket Flash atau hub *363#      2
4                                          4.5GB/30 hari hanya Rp 55 Ribu Spesial buat anda yang terpilih. Aktifkan sekarang juga di *550*907# Buruan..! SKB      2

In [ ]:
from sklearn.model_selection import train_test_split
%time
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 7.39 µs

In [ ]:
print("Training SVC")
%time
svc.fit(X_train, y_train)

Training SVC
CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 6.91 µs

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

y_true = y_test
y_pred = svc.predict(X_test)
matrix = confusion_matrix(y_true, y_pred)

label_names = pd.Series(['normal', 'penipuan', 'penawaran'])
pd.DataFrame(matrix,
     columns='Predicted ' + label_names,
     index='Is ' + label_names)

              Predicted normal  Predicted penipuan  Predicted penawaran
Is normal                  199                   2                    5
Is penipuan                  5                 150                    8
Is penawaran                 6                  11                  114

In [ ]:
y_true = y_test
y_pred = svc.predict(X_test)
matrix = confusion_matrix(y_true, y_pred)

label_names = pd.Series(['normal', 'penipuan', 'penawaran'])
pd.DataFrame(matrix,
     columns='Predicted ' + label_names,
     index='Is ' + label_names).div(matrix.sum(axis=1), axis=0)

              Predicted normal  Predicted penipuan  Predicted penawaran
Is normal             0.966019            0.009709             0.024272
Is penipuan           0.030675            0.920245             0.049080
Is penawaran          0.045802            0.083969             0.870229

In [ ]:
print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.97      0.96       206
           1       0.92      0.92      0.92       163
           2       0.90      0.87      0.88       131

    accuracy                           0.93       500
   macro avg       0.92      0.92      0.92       500
weighted avg       0.93      0.93      0.93       500